### ISSUE TITLE
Craft a get_incoming_transactions method for wallet

### ISSUE THREAD

**Issue by lalvarezguillen** [python-monero/monero-python#1]
We need a `get_incoming_transactions` method that doesn't discard the transactions in `pool` when a `min_height` is provided.

It'd be also nice to be able to expose the Wallet RPC's parameter that allows filtering transactions by the index of the subaddress they were addressed to.

**Comment by lalvarezguillen** [comment]
I'm working on this

**Comment by dethos** [comment]
This was implemented on #8, closing the issue. Feel free to reopen if something is missing.
