### ISSUE TITLE
to_atomic raises MemoryError when receiving a str

### ISSUE THREAD

**Issue by lalvarezguillen** [python-monero/monero-python#12]
Maybe we can do some type checking inside `to_atomic`, and raise TypeErrors?

**Comment by dethos** [comment]
@lalvarezguillen if I'm not mistaken this was already fixed on the upstream project (https://github.com/monero-ecosystem/monero-python/commit/a7c8579b139c75e20472f5aea36aa7ed6cb17b03). Perhaps we should sync the latest changes into our fork.

**Comment by lalvarezguillen** [comment]
we should definitely sync
