### ISSUE TITLE
Consider extending logging with timing of requests

### ISSUE THREAD

**Issue by lalvarezguillen** [python-monero/monero-python#17]
Could it make sense to extend the logging of this library with measures of the time that a request took? It'd be pretty easy, since that kind of logging is isolated on the `raw_request` methods of `JSONRPCWallet` and `JSONRPCDaemon`

I can see the info being very useful

**Comment by dethos** [comment]
@lalvarezguillen do you see it being useful for debugging or for providing some kind of metric on a production system?

The correct logging level depends on this information.

**Comment by lalvarezguillen** [comment]
Good question. I think it could fulfill both roles.
