### ISSUE TITLE
Consider logging RPC calls

### ISSUE THREAD

**Issue by lalvarezguillen** [python-monero/monero-python#2]
We might want to log as `debug` the arguments and result of RPC calls.

This might be an optional feature, something that can be switched on and off

**Comment by dethos** [comment]
@lalvarezguillen the code already contains this logic. You just need to configure your application to log the `debug` level. 

For example if you do this on your application:
```python
import logging

logger = logging.getLogger()
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.setLevel(logging.DEBUG)
```
`monero-python`'s code will log to the `stdout` all information related to the RPC requests and responses.

**Comment by lalvarezguillen** [comment]
Glad some logging logic is in place.

Do you think there's any reason to replace `logging` with `structlog`?

**Comment by dethos** [comment]
Since this is a library I don't see a reason to replace. This will be used by application developers and they should decide what fits their logging needs, so sticking with standard to me seems the right choice.

**Comment by dethos** [comment]
@lalvarezguillen can we close this issue? 

Later we can discuss a change of logging package in a dedicated issue, if there is strong support for it.

**Comment by lalvarezguillen** [comment]
Sure. Closing
